version: "3.3"

services:
  cat:
    image: cat
    container_name: cat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    runtime: nvidia
    #ipc: host
    #network_mode: host
    shm_size: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    #command: "python3 app.py"
    command: gunicorn -w 1 -t 10000 --bind 0.0.0.0:8008 app:create_app'("SAUD")'
